EveraWebApp/Models/Popular.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace EveraWebApp.Models
{
    public class Popular
    {
        public int Id { get; set; }
        public string Title { get; set; } = null!;
        public string? ImageName { get; set; }
       
        [NotMapped]
        public IFormFile Image { get; set; } = null!;
    }
}

EveraWebApp/Areas/Admin/Controllers/PopularController.cs
using EveraWebApp.DataContext;
using EveraWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;
using System.Runtime.Intrinsics.X86;

namespace EveraWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PopularController : Controller
    {
        private readonly EveraDbContext _everaDbContext;
        private readonly IWebHostEnvironment _environment;
        public PopularController(EveraDbContext everaDbContext, IWebHostEnvironment environment)
        {
            _everaDbContext = everaDbContext;
            _environment = environment;
        }
        public async Task<IActionResult> Index()
        {
            List<Popular> populars =  await _everaDbContext.Populars.ToListAsync();
           
            return View(populars);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Popular? popular=await _everaDbContext.Populars.FindAsync(id);
            if (popular == null) return NotFound();
            if(popular.ImageName!=null)
            {
                string filePath = Path.Combine(_environment.WebRootPath, "assets", "imgs", "shop");
                if(System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
            }
            _everaDbContext.Populars.Remove(popular);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Popular popular)
        {
            if(!ModelState.IsValid) return View();
            if(_everaDbContext.Populars.Any(p=>p.Title.Trim().ToLower()== popular.Title.Trim().ToLower()))
            {
                ModelState.AddModelError("Title", "Already title exist!");
                return View();
            }
            if (popular.Image == null)
            {
                ModelState.AddModelError("Image", "Image is null");
            }

            string guid=Guid.NewGuid().ToString();
            string newFilename = guid + popular.Image.FileName;
            string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "shop", newFilename);

            using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
            {
                await popular.Image.CopyToAsync(fileStream);
            }

            popular.ImageName = newFilename;
            await _everaDbContext.Populars.AddAsync(popular);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Read(int id)
        {
            Popular? popular = await _everaDbContext.Populars.FindAsync(id);
            if (popular == null) return NotFound();
            return View(popular);
        }
        public async Task<IActionResult> Update(int id)
        {
            Popular? popular = await _everaDbContext.Populars.FindAsync(id);
            if (popular == null) return NotFound();
            return View(popular);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Popular newPopular)
        {
            Popular? popular= await _everaDbContext.Populars.AsNoTracking().Where(p=>p.Id== id).FirstOrDefaultAsync();

            if (popular == null) return NotFound();
            if (ModelState["Title"].Errors.Any()) return View(newPopular);

            if(newPopular.Image != null)
            {
                string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "shop", popular.ImageName);
                using(FileStream fileStream=new FileStream(path, FileMode.Create))
                {
                    await newPopular.Image.CopyToAsync(fileStream);
                }
                 newPopular.ImageName = popular.ImageName;
            }
            else  newPopular.ImageName=popular.ImageName;

            _everaDbContext.Populars.Update(newPopular);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

EveraWebApp/Areas/Admin/Views/Popular/Create.cshtml
@model Popular

<div>
<h1>Popular Create</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
         <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Title"></span>
         </div>
        
         <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
         </div>
         <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

EveraWebApp/Areas/Admin/Views/Popular/Index.cshtml
@model List<Popular>
@{
    int Count = 0;
}
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-danger text-center">Popular categories</h1>
      
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                <div>
                    <a class="btn btn-success px-5" asp-controller="Popular" asp-action="Create">Create</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Title</th>
                                <th>Image</th>
                                <th>Settings</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Popular item in Model)
                            {
                                <tr>
                                    <td>@(++Count)</td>
                                    <td> @item.Title</td>
                                    <td><img style="width:200px;" src="~/assets/imgs/shop/@item.ImageName" /></td>
                                        <td>
                                        <div class="container d-flex justify-content-around">
                                                    <a asp-controller="Popular" asp-action="Read" asp-route-id="@item.Id" ><button class="btn btn-info">Details</button></a>
                                                        <form asp-controller="Popular" asp-action="Update" asp-route-id="@item.Id" method="get">
                                                    <a><button class="btn btn-warning">Edit</button></a>
                                                </form>
                                                        <form asp-controller="Popular" method="post" asp-action="Delete" asp-route-id="@item.Id">
                                                        <a><button type="submit" class="btn btn-danger">Delete</button></a>
                                                </form>
                                        </div>
                                        </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

EveraWebApp/Areas/Admin/Views/Popular/Read.cshtml
@model Popular

<div>
    <h1>@Model.Id</h1>
    <h1>@Model.Title</h1>
    <h1>@Model.Image</h1>
</div>

EveraWebApp/Areas/Admin/Views/Popular/Update.cshtml
@model Popular

<div>
<h1>Slider Update</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
         <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Title"></span>
         </div>
        
         <img style="width:200px" src="~/assets/imgs/shop/@Model.ImageName"/>
          <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
         </div>
         <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>