EveraWebApp/Models/Brand.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace EveraWebApp.Models
{
    public class Brand
    {
        public int Id { get; set; }
        public string? ImageName { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; } = null!;
    }
}

EveraWebApp/Areas/Admin/Controllers/BrandController.cs
using EveraWebApp.DataContext;
using EveraWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EveraWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandController : Controller
    {
        private readonly EveraDbContext _everaDbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public BrandController(EveraDbContext everaDbContext,IWebHostEnvironment webHostEnvironment)
        {
            _everaDbContext = everaDbContext;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            List<Brand> brands = await _everaDbContext.Brands.ToListAsync();
            return View(brands);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Brand? brand=await _everaDbContext.Brands.FindAsync(id);
            if(brand == null) return NotFound();

            if(brand.ImageName!=null)
            {
                string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "imgs", "banner");
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
            }
            _everaDbContext.Brands.Remove(brand);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Brand brand)
        {
            if (!ModelState.IsValid) return View();
            
            string guid=Guid.NewGuid().ToString();
            string newFilename = guid + brand.Image.FileName;
            string path = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "imgs", "banner", newFilename);

            using(FileStream fileStream=new FileStream(path, FileMode.CreateNew))
            {
                await brand.Image.CopyToAsync(fileStream);
            }

            brand.ImageName = newFilename;

            await _everaDbContext.Brands.AddAsync(brand);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Read(int id)
        {
            Brand? brand = await _everaDbContext.Brands.FindAsync(id);
            if (brand == null) return NotFound();
            return View(brand);
        }
        public async Task<IActionResult> Update(int id)
        {
            Brand? brand = await _everaDbContext.Brands.FindAsync(id);
            if (brand == null) return NotFound();
            return View(brand);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id,Brand newBrand)
        {
            Brand? brand = await _everaDbContext.Brands.AsNoTracking().Where(b=>b.Id== id).FirstOrDefaultAsync();

            if (brand == null) return NotFound();
            if(!ModelState.IsValid)  return View(newBrand);
            if (newBrand != null)
            {
                string path = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "imgs", "banner", newBrand.ImageName);
                using (FileStream fileStream = new FileStream(path, FileMode.Create))
                {
                    await newBrand.Image.CopyToAsync(fileStream);
                }
                newBrand.ImageName = brand.ImageName;
            }
            else newBrand.ImageName = brand.ImageName;

            newBrand.Id=brand.Id;

             _everaDbContext.Brands.Update(newBrand);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

EveraWebApp/Areas/Admin/Views/Brand/Create.cshtml
@model Brand

<div>
<h1>Brand Create</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
        
         <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
         </div>
         <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

EveraWebApp/Areas/Admin/Views/Brand/Index.cshtml
@model List<Brand>
@{
    int Count = 0;
}
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-danger text-center">Featured Brands</h1>
        
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                <div>
                    <a class="btn btn-success px-5" asp-controller="Brand" asp-action="Create">Create</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Image</th>
                                <th>Settings</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Brand item in Model)
                            {
                                <tr>
                                    <td>@(++Count)</td>
                                        <td><img style="width:200px;" src="~/assets/imgs/banner/@item.ImageName" /></td>
                                        <td>
                                        <div class="container d-flex justify-content-around">
                                                <a asp-controller="Brand" asp-action="Read" asp-route-id="@item.Id" ><button class="btn btn-info">Details</button></a>
                                                    <form asp-controller="Brand" asp-action="Update" asp-route-id="@item.Id" method="get">
                                                    <a><button class="btn btn-warning">Edit</button></a>
                                                </form>
                                                    <form asp-controller="Brand" method="post" asp-action="Delete" asp-route-id="@item.Id">
                                                        <a><button type="submit" class="btn btn-danger">Delete</button></a>
                                                </form>
                                        </div>
                                        </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->

</div>

EveraWebApp/Areas/Admin/Views/Brand/Read.cshtml
@model Brand

<div>
    <h1>@Model.Id</h1>
    <h1>@Model.ImageName</h1>
  
</div>

EveraWebApp/Areas/Admin/Views/Brand/Update.cshtml
@model Brand

<div>
<h1>Slider Update</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
        
         <img style="width:200px" src="~/assets/imgs/banner/@Model.ImageName"/>
          <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
         </div>
         <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>