EveraWebApp/Models/Slider.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EveraWebApp.Models
{
    public class Slider
    {
        public int Id { get; set; }
        [Required,MaxLength(100)]
        public string Title { get; set; } = null!;
        public string? Description { get; set; }
        public string ImageName { get; set; }=null!;
      
    }
}

EveraWebApp/Areas/Admin/Controllers/SliderController.cs
using EveraWebApp.DataContext;
using EveraWebApp.Models;
using EveraWebApp.ViewModels.SliderVM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Drawing.Drawing2D;
using System.Drawing.Text;

namespace EveraWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly EveraDbContext _everaDbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public SliderController(EveraDbContext everaDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _everaDbContext = everaDbContext;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            List<Slider> sliders = await _everaDbContext.Sliders.ToListAsync();
            return View(sliders);
        }
      
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSliderVM slider)
        {
            if(!ModelState.IsValid) return View();

            if(_everaDbContext.Sliders.Any(s=>s.Title.Trim().ToLower() == slider.Title.Trim().ToLower()))
            {
                ModelState.AddModelError("Title", "Already title exsit!");
                return View();
            }
            string guid = Guid.NewGuid().ToString();
            string newFilename =guid+ slider.Image.FileName;
            string path = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "imgs", "slider",newFilename);
         
            using (FileStream fileStream =new FileStream(path, FileMode.CreateNew))
            {
                await slider.Image.CopyToAsync(fileStream);
            }
            Slider newSlider = new Slider()
            {
                Description= slider.Description,
                Title= slider.Title,
                ImageName=newFilename
            };
          
            await _everaDbContext.Sliders.AddAsync(newSlider);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
       
        public async Task<IActionResult> Read(int id)
        {
            Slider? slider = await _everaDbContext.Sliders.FindAsync(id);
            if(slider== null) return NotFound();
            return View(slider);
        }
     
        public async Task<IActionResult> Update(int id)
        {
            Slider? slider = await _everaDbContext.Sliders.FindAsync(id);
            if(slider==null) return NotFound();
            UpdateSliderVM updateSliderVM= new UpdateSliderVM()
            {
                Description= slider.Description,
                ImageName= slider.ImageName,
                Title= slider.Title
            };
            return View(updateSliderVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, UpdateSliderVM newSlider)
        {
            if (_everaDbContext.Sliders.Any(s => s.Title.Trim().ToLower() == newSlider.Title.Trim().ToLower()))
            {
                ModelState.AddModelError("Title", "Already title exsit!");
                return View();
            }
            Slider? slider = await _everaDbContext.Sliders.AsNoTracking().Where(s=>s.Id==id).FirstOrDefaultAsync();
            if (slider == null) return NotFound();
            if (!ModelState.IsValid)
            {
                return View(newSlider);
            }
            if(newSlider.Image != null)
            {
                 string path = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "imgs", "slider",slider.ImageName);
                 using (FileStream fileStream = new FileStream(path, FileMode.Create))
                {
                     await  newSlider.Image.CopyToAsync(fileStream);
                }
                 newSlider.ImageName=slider.ImageName;
            }
            else
            {
                  newSlider.ImageName=slider.ImageName;
            }
            Slider newDbSlider=new Slider()
            {
                Id=slider.Id,
                Title=newSlider.Title,
                Description=newSlider.Description,
                ImageName=newSlider.ImageName
            };
            _everaDbContext.Sliders.Update(newDbSlider);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Slider? slider = await _everaDbContext.Sliders.FindAsync(id);
            if (slider == null) return NotFound();

            if (slider.ImageName != null)
            {
                string filePath=Path.Combine(_webHostEnvironment.WebRootPath,"assets","imgs","slider");
                if(System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
            }

            _everaDbContext.Sliders.Remove(slider);
            await _everaDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

EveraWebApp/Areas/Admin/Views/Slider/Create.cshtml
@model CreateSliderVM

<div>
<h1>Slider Create</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
         <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Title"></span>
         </div>
         <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Description"></span>
         </div>
         <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
         </div>
         <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

EveraWebApp/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    int Count = 0;
}
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-danger text-center">Sliders</h1>
 
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                <div>
                    <a class="btn btn-success px-5" asp-controller="Slider" asp-action="Create">Create</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Settings</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Slider item in Model)
                            {
                                    <tr>
                                        <td>@(++Count)</td>
                                        <td><img style="width:200px;" src="~/assets/imgs/slider/@item.ImageName" /></td>
                                        <td> @item.Title</td>
                                        <td>@item.Description</td>
                                          <td>
                                            <div class="container d-flex justify-content-around">
                                                    <a asp-controller="Slider" asp-action="Read" asp-route-id="@item.Id" ><button class="btn btn-info">Details</button></a>
                                                    <form asp-controller="Slider" asp-action="Update" asp-route-id="@item.Id" method="get">
                                                        <a><button class="btn btn-warning">Edit</button></a>
                                                    </form>
                                                    <form asp-controller="Slider" method="post" asp-action="Delete" asp-route-id="@item.Id">
                                                           <a><button class="btn btn-danger">Delete</button></a>
                                                    </form>
                                            </div>
                                          </td>
                                    </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->

</div>

EveraWebApp/Areas/Admin/Views/Slider/Read.cshtml
@model Slider

<div>
    <h1>@Model.Id</h1>
    <h1>@Model.Title</h1>
    <h1>@Model.Description</h1>
</div>

EveraWebApp/Areas/Admin/Views/Slider/Update.cshtml
@model UpdateSliderVM

<div>
<h1>Slider Update</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
         <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Title"></span>
         </div>
         <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Description"></span>
         </div>
         <img style="width:200px" src="~/assets/imgs/slider/@Model.ImageName"/>
          <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
         </div>
         <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>